conversation/urls.py
from django.urls import path
from . import views

app_name ='conversation'

urlpatterns = [
    path('', views.inbox, name='inbox'),
    path('new/<int:item_pk>/', views.new_conversation, name='new'),
    path('<int:pk>/', views.detail, name='detail'),
]   

core/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views
from .forms import LoginForm
app_name = 'core'

urlpatterns = [
    path('',views.index, name='index'),
    path('contact/', views.contact, name='contact' ),
    path('signup/',views.signup, name='signup'),
    path('login/', auth_views.LoginView.as_view(template_name='core/login.html',authentication_form = LoginForm), name='login'),
    path('logout/', views.logout_view, name='logout'),
]   

dashboard/urls.py
from django.urls import path, include
from . import views

app_name='dashboard'

urlpatterns = [
    path('',views.index, name='index'),
    path('delete/', views.deleteUsers, name='delete'),
    path('promote/<int:pk>/', views.promoteUser, name='promote'),
    path('add-category/', views.add_category, name='add_category'),
    path('items/', include('item.urls')),
]

item/urls.py
from django.urls  import path,include
from  . import views

app_name = 'item'

urlpatterns = [
    path('',views.items, name='items'),
    path('<int:pk>/', views.detail, name = 'detail'),
    path('new/',views.new, name='new'),
    path('<int:pk>/delete', views.delete, name = 'delete'),
    path('<int:pk>/edit', views.edit, name = 'edit'),


     
]

marketplace/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
urlpatterns = [
    path('',include('core.urls')),
    path('items/', include('item.urls')),
    path('admin/', admin.site.urls),
    path('dashboard/', include('dashboard.urls')),
    path('inbox/',include('conversation.urls')),

] +  static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

core/models.py
from django.db import models

# Create your models here.

core/forms.py
from django import forms 
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User

class LoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder':'Enter your username',
        'class':'w-full py-4 px-6 dark:text-black rounded-xl'
    }))   
    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder':'Enter your password',
        'class':'w-full py-4 px-6 dark:text-black rounded-xl'
    }))
class SignupForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username','email','password1','password2')

    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder':'Enter your username',
        'class':'w-full py-4 px-6   dark:text-black rounded-xl'
    }))
    email = forms.CharField(widget=forms.EmailInput(attrs={
        'placeholder':'Enter your email',
        'class':'w-full py-4 px-6   dark:text-black rounded-xl'
    }))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder':'Enter your password',
        'class':'w-full py-4 px-6  dark:text-black  rounded-xl'
    }))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder':'Check your password',
        'class':'w-full py-4 px-6   dark:text-black rounded-xl'
    }))

core/views.py
from django.shortcuts import render,redirect
from item.models import Category, Item
from django.contrib.auth import logout, login

from .forms import SignupForm

def index(request):
    items = Item.objects.filter(is_sold=False)[0:6]
    categories = Category.objects.all()
    return render(request,'core/index.html',{
        'categories':categories,
        'items':items,
    })

def contact(request):
    return render(request, 'core/contact.html')

def signup(request):
    if request.method == 'POST':
        form = SignupForm(request.POST)

        if form.is_valid():
            user = form.save(commit=False)
            user.email = form.cleaned_data['email'].lower()
            user.username = form.cleaned_data['username'].lower()
            user.save()
            login(request, user)
            return redirect('/login/')
    else:
        form = SignupForm()

    return render(request,'core/signup.html',{
        'form':form,
    })

def logout_view(request):
    logout(request)
    return redirect('/login/')  # Replace 'home' with the name of the URL pattern for your home page

core/templates/core/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" href="{% static 'favicon.png' %}" type="image/x-icon">
    <script src="https://cdn.tailwindcss.com"></script>
    <title>{% block title %}{% endblock title %} | RE-SELL</title>
</head>
<body class="dark:bg-gray-900">
    <nav class="dark:text-white py-6 sm:px-6 w-full sm:flex flex-wrap justify-between items-center border-b border-gray-200">
            <a href="/" class="md:text-xl font-semibold ">RE-SELL<span class="font-light"> | {{ request.user.username }}</span></a>


            
        <div class="md:flex  md:space-x-6">
            <div class="flex items-center justify-end sm:space-x-6">
                <a href="{% url 'item:new' %}" class=" m-3 sm:text-lg font-semibold hover:text-gray-500">New item</a>
                <a href="{% url 'item:items' %}" class=" m-3 sm:text-lg font-semibold hover:text-gray-500">Browse</a>
            </div>
    
            {% if request.user.is_authenticated %}
                <div class="flex items-center justify-center sm:space-x-6 space-x-3">
                    <a href="{% url 'conversation:inbox' %}" class="px-6   sm:py-3 sm:text-lg font-semibold bg-teal-500 text-white rounded-xl hover:bg-teal-700">Inbox</a>
                    <a href="{% url 'dashboard:index' %}" class="px-6  sm:py-3 sm:text-lg font-semibold bg-gray-500 text-white rounded-xl hover:bg-gray-700">Dashboard</a>
                    <a href="{% url 'core:logout' %}" class="px-3  sm:py-3 sm:text-lg font-semibold bg-red-500 text-white rounded-xl hover:bg-red-700">Logout</a>
                </div>
            {% else %}
                <div class="flex items-center justify-center space-x-6">
                    <a href="{% url 'core:signup' %}" class="px-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl hover:bg-teal-700">Sign up</a>
                    <a href="{% url 'core:login' %}" class="px-6 py-3 text-lg font-semibold bg-gray-500 text-white rounded-xl hover:bg-gray-700">Login</a>
                </div>
            {% endif %}
        </div>
    </nav>
    
    
    
    <div class="px-6 py-6">
        {% block content %}
        {% endblock %}
    </div>

    <footer  class="py-6 px-6 flex justify-between bg-gray-800">
        <div class="w-2/3 pr-10">
            <h3 class="mb-5 font-semibold text-gray-400">About</h3>
            <p class="text-lg text-gray-500 break-words">
                RE-SELL is a cutting-edge online e-commerce platform designed to revolutionize the way you shop. We bring together a vast range of products from various sellers, providing you with a convenient, secure, and immersive shopping experience. Whether you're searching for the latest fashion trends, high-quality electronics, home decor, or everyday essentials, Marketplace has got you covered.    
            </p>
        </div>
        <div class="w-1/3">
            <h3 class="mb-5 font-semibold text-gray-400">Menu</h3>

            <ul class="space-y-2">
                <li><a href="#" class="text-lg text-teal-500 hover:text-teal-700">About</a></li>
                <li><a href="{% url 'core:contact' %}" class="text-lg text-teal-500 hover:text-teal-700">Contact</a></li>
                <li><a href="#" class="text-lg text-teal-500 hover:text-teal-700">Privacy policy</a></li>
                <li><a href="#" class="text-lg text-teal-500 hover:text-teal-700">Terms of use</a></li>

            </ul>
        </div>
    </footer>
</body>
</html>

core/templates/core/contact.html
{% extends 'core/base.html' %}

{% block title %}Contact{% endblock title %}

{% block content %}
    <h1 class="text-2xl font-medium text-center dark:text-white ">Contact us</h1>

<div class="sm:flex  justify-evenly">
    <div class="p-6 m-6 rounded-xl shadow-xl bg-gray-100">
        <h2 class="text-xl font-medium mb-3 ">
            Customer Support
        </h2>
        <p>
        Phone: +1-XXX-XXX-XXXX <br>
        Email: support@resell.com <br>
        </p>
    </div>
    <div class="p-6 m-6 rounded-xl shadow-xl bg-gray-100">
        <h2 class="text-xl font-medium mb-3">
            Seller Inquiries
        </h2>
        <p>
            Email: sellers@resell.com <br>

            Media and Press Inquiries: <br>
            
            Email: media@resell.com <br>
        </p>
    </div>
    <div class="p-6 m-6 rounded-xl shadow-xl bg-gray-100">
        <h2 class="text-xl font-medium mb-3">
            Corporate Headquarters
        </h2>
        <p>
            RE-SELL Inc. <br>
            144411 <br>
            Phagwara, Punjab <br>
            India <br>
        </p>
    </div>
    <div class="p-6 m-6 rounded-xl shadow-xl bg-gray-100">
        <h2 class="text-xl font-medium mb-3">
            Social Media
        </h2>
            <a href="#">Facebook</a><br>
            <a href="#">Instagram</a><br>
            <a href="#">LinkedIn</a><br>
    </div>


</div>



{% endblock %}

core/templates/core/index.html
{% extends 'core/base.html' %}

{% block title %}Welcome {% endblock title %}

{% block content %}
<!-- <div
    class="mt-6 sm:px-6 px-3 w-full py-12 dark:text-white dark:bg-gray-800 dark:text-white bg-gray-100 rounded-xl shadow-xl">
    <h2 class="md:mb-12 mb-3 font-medium text-2xl text-center">Newest items</h2>

    <div class="grid grid-cols-2 md:grid-cols-3  lg:grid-cols-4 items-stretch gap-3  ">
        {% for item in items %}
        <div class="shadow-xl h-fit  rounded-b-xl  ">
            <a href="{% url 'item:detail' item.id %}">
                <div class="md:shrink-0">
                    <img src="{{ item.image.url }}" class="w-full rounded-t-lg dark:brightness-50 " alt="Product image">
                </div>
                <div
                    class="p-6 p-3 bg-white dark:bg-gray-900 flex flex-wrap sm:justify-between justify-center  rounded-b-xl ">
                    <div>
                        <h2 class="sm:text-2xl break-words">{{ item.name }}</h2>
                        <p class="text-gray-500">₹{{item.price}}</p>
                    </div>
                    <div>
                        <p class=" hidden sm:block bg-gray-200 dark:bg-gray-800 sm:px-3 sm:py-2  rounded-xl">{{
                            item.category }}</p>
                    </div>
                </div>
            </a>
        </div>

        {% endfor %}

    </div>

</div> -->

<div class="mt-6 sm:px-6 px-3 w-full py-12 dark:text-white dark:bg-gray-800 dark:text-white bg-gray-100 rounded-xl shadow-xl">
    <h2 class="md:mb-12 mb-3 font-medium text-2xl text-center">Newest items</h2>

    <div class="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-4 items-stretch gap-3">
        {% for item in items %}
        <div class="shadow-xl rounded-b-xl">
            <a href="{% url 'item:detail' item.id %}">
                <div class="md:shrink-0 overflow-hidden rounded-t-lg">
                    <img src="{{ item.image.url }}" class="w-full object-cover h-90 dark:brightness-50" alt="Product image">
                </div>
                <div class="p-6 p-3 bg-white dark:bg-gray-900 flex flex-wrap sm:justify-between justify-center rounded-b-xl">
                    <div>
                        <h2 class="sm:text-2xl break-words">{{ item.name }}</h2>
                        <p class="text-gray-500">₹{{ item.price }}</p>
                    </div>
                    <div>
                        <p class="hidden sm:block bg-gray-200 dark:bg-gray-800 sm:px-3 sm:py-2 rounded-xl">{{ item.category }}</p>
                    </div>
                </div>
            </a>
        </div>
        {% endfor %}
    </div>
</div>



<div class="mt-6 sm:px-6 px-3 py-12 bg-gray-100 dark:bg-gray-900 dark:text-white rounded-xl shadow-2xl">
    <h2 class="mb-12 text-2xl text-center font-medium">Categories</h2>

    <div class="grid grid-cols-2 sm:grid-cols-3 sm:gap-3 gap-2">
        {% for category in categories %}

        <div>
            <a href="{% url 'item:items' %}?category={{category.id}}">
                <div class="p-6  bg-white dark:bg-gray-800 rounded-xl shadow-xl">
                    <h2 class="sm:text-2xl break-words">{{ category.name }}</h2>
                    <p class="text-gray-500">{{category.items.count}} items</p>
                </div>
            </a>
        </div>


        {% endfor %}
    </div>
</div>

{% endblock %}

core/templates/core/login.html
{% extends 'core/base.html' %}

{% block title %}Sign up{% endblock title %}

{% block  content %}

<div class="md:w-1/2 my-6 p-6 mx-auto bg-gray-100 dark:bg-gray-800 dark:text-white rounded-xl">
    <h1 class="mb-6 text-3xl">Login</h1>

    <form action="" method="post">
        {% csrf_token %}

        <div class="mb-3">
            <label for="" class="inline-block mb-2 ">Username</label><br>
            {{ form.username }}
        </div> 
        {% comment %} <div class="mb-3">
            <label for="" class="inline-block mb-2">Email</label><br>
            {{ form.email }}
        </div> {% endcomment %}
        <div class="mb-3">
            <label for="" class="inline-block mb-2 ">Password</label><br>
            {{ form.password }}
        </div>

        {% if form.errors or form.non_field_errors %}
            <div class="mb-3 p-6 dark:bg-red-500 bg-red-100 rounded-xl">
                {% for field in form %}
                    {{ field.errors }}
                {% endfor %}
        {{ form.non_field_errors }}
            </div>
        {% endif %}
        <button class="py-3 px-8 w-full text-lg bg-teal-500 hover:bg-teal-700 rounded-xl text-white">Submit</button>
    </form>

</div>


{% endblock  %}

core/templates/core/signup.html
{% extends 'core/base.html' %}

{% block title %}Sign up{% endblock title %}

{% block  content %}

<div class="md:w-1/2 my-6 p-6 mx-auto bg-gray-100 dark:text-white dark:bg-gray-800 rounded-xl">
    <h1 class="mb-6 text-3xl">Sign up</h1>

    <form action="" method="post">
        {% csrf_token %}

        <div class="mb-3">
            <label for="" class="inline-block mb-2">Username</label><br>
            {{ form.username }}
        </div>
        <div class="mb-3">
            <label for="" class="inline-block mb-2">Email</label><br>
            {{ form.email }}
        </div>
        <div class="mb-3">
            <label for="" class="inline-block mb-2">Password</label><br>
            {{ form.password1 }}
        </div>
        <div class="mb-3">
            <label for="" class="inline-block mb-2">Check password</label><br>
            {{ form.password2 }}
        </div>

        {% if form.errors or form.non_field_errors %}
            <div class="mb-3  dark:bg-red-500   p-6 bg-red-100 rounded-xl">
                {% for field in form %}
                    
                {{ field.errors }}
                {% endfor %}
                {{ form.non_field_errors }}

            </div>
        {% endif %}
        <button class="py-3 px-8 w-full text-lg bg-teal-500 hover:bg-teal-700 rounded-xl text-white">Submit</button>
    </form>

</div>


{% endblock  %}