conversation/urls.py
from django.urls import path
from . import views

app_name ='conversation'

urlpatterns = [
    path('', views.inbox, name='inbox'),
    path('new/<int:item_pk>/', views.new_conversation, name='new'),
    path('<int:pk>/', views.detail, name='detail'),
]   

core/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views
from .forms import LoginForm
app_name = 'core'

urlpatterns = [
    path('',views.index, name='index'),
    path('contact/', views.contact, name='contact' ),
    path('signup/',views.signup, name='signup'),
    path('login/', auth_views.LoginView.as_view(template_name='core/login.html',authentication_form = LoginForm), name='login'),
    path('logout/', views.logout_view, name='logout'),
]   

item/urls.py
from django.urls  import path,include
from  . import views

app_name = 'item'

urlpatterns = [
    path('',views.items, name='items'),
    path('<int:pk>/', views.detail, name = 'detail'),
    path('new/',views.new, name='new'),
    path('<int:pk>/delete', views.delete, name = 'delete'),
    path('<int:pk>/edit', views.edit, name = 'edit'),


     
]

marketplace/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
urlpatterns = [
    path('',include('core.urls')),
    path('items/', include('item.urls')),
    path('admin/', admin.site.urls),
    path('dashboard/', include('dashboard.urls')),
    path('inbox/',include('conversation.urls')),

] +  static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

item/models.py
from django.db import models
from django.contrib.auth.models import User

class Category(models.Model):
    name=models.CharField(max_length=255, unique=True)
    
    class Meta:
        ordering = ('name',)
        verbose_name_plural = 'Categories'    
    
    def __str__(self):
        return self.name
    

class Item(models.Model):
    category = models.ForeignKey(Category, related_name='items', on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    description = models.TextField(blank=True,null=True)
    size = models.CharField(max_length=100,blank=True,null=True)
    color = models.CharField(max_length=100,blank=True,null=True)
    gender = models.CharField(max_length=100,blank=True,null=True)
    price=models.FloatField(default=0.0)
    image = models.ImageField(upload_to='item_images', blank=True, null=True)
    is_sold = models.BooleanField(default=False)
    created_by = models.ForeignKey(User, on_delete=models.CASCADE, related_name='items')
    created_at=models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return self.name

item/forms.py
from django import forms 

from . models import Item

INPUT_CLASSES = 'w-full py-4 px-6 rounded-xl border dark:text-white dark:bg-gray-900'
SIZE_CHOICES = [
        ('','None'),
        ('S', 'S'),
        ('M', 'M'),
        ('L', 'L'),
        ('XL', 'XL'),
        ('XXL', 'XXL'),
    ]
COLOR_CHOICES = [
        ('','None'),
        ('Red', 'Red'),
        ('Blue', 'Blue'),
        ('Violet', 'Violet'),
        ('Orange', 'Orange'),
        ('Black', 'Black'),
        ('Green', 'Green'),
        ('White', 'White'),
    ]

GENDER_CHOICES = [
        ('','Not specified'),
        ('Male', 'Male'),
        ('Female', 'Female'),
        ('Other', 'Other'),
    ]

class NewItemForm(forms.ModelForm):

    # size = forms.ChoiceField(choices=SIZE_CHOICES)
    class Meta:
        model = Item
        fields = ('image','category','name','price','size','color','gender','description',)

        widgets = {
            'category':forms.Select(attrs={
                'class':INPUT_CLASSES
            }),
            'name':forms.TextInput(attrs={
                'class':INPUT_CLASSES
            }),
            'description':forms.Textarea(attrs={
                'class':INPUT_CLASSES,
                'rows':4
            }),
            'price':forms.TextInput(attrs={
                'class':INPUT_CLASSES
            }),
            'image':forms.FileInput(attrs={
                'class':INPUT_CLASSES
            }),
            'size':forms.Select(attrs={
                'class':INPUT_CLASSES
            },choices=SIZE_CHOICES),
            'color':forms.SelectMultiple(attrs={
                'class':INPUT_CLASSES
            },choices=COLOR_CHOICES),
            'gender':forms.Select(attrs={
                'class':INPUT_CLASSES
            },choices=GENDER_CHOICES),
        }
        empty_label = 'Select category'
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['category'].empty_label = 'Select category'
        self.fields['category'].initial = ''


# edit

class EditItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = ('is_sold','image','name','size','color','description',)

        widgets = {
            'name':forms.TextInput(attrs={
                'class':INPUT_CLASSES
            }),
            'description':forms.Textarea(attrs={
                'class':INPUT_CLASSES,
                'rows':4
            }),
            'image':forms.FileInput(attrs={
                'class':INPUT_CLASSES
            }),
            'size':forms.Select(attrs={
                'class':INPUT_CLASSES
            },choices=SIZE_CHOICES),
            'color':forms.SelectMultiple(attrs={
                'class':INPUT_CLASSES
            },choices=COLOR_CHOICES),
            'is_sold':forms.CheckboxInput(attrs={
                'class':'text-left accent-emerald-500/25 w-5 h-5'
            }),
        }

item/views.py
from django.shortcuts import render,get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from .forms import NewItemForm, EditItemForm
from .models import Item, Category

from django.db.models import Q 

def items(request):
    query = request.GET.get('query','')
    items = Item.objects.filter(is_sold=False)
    categories = Category.objects.all()
    category_id = request.GET.get('category',0)

    if category_id:
        items = items.filter(category_id=category_id)

    if query:
        items = items.filter(Q(name__icontains=query)|
                             Q(description__icontains=query))
    
    
    return render(request, 'item/items.html',{
        'items':items,
        'query':query,
        'categories':categories,
        'category_id':int(category_id),
    })

def detail(request, pk):
    item = get_object_or_404(Item, pk=pk)
    related_items = Item.objects.filter(category=item.category).exclude(pk=pk)[:3]

    if item.color:
        item.color = item.color.replace(',', ' ')
        item.color = item.color.replace('[', '')
        item.color = item.color.replace(']', '')
        item.color = item.color.replace("'", '')




    
    return render(request, 'item/detail.html',{
        'item':item,
        'related_items':related_items,
    })

@login_required
def new(request):
    if request.method == 'POST':
        form = NewItemForm(request.POST, request.FILES)
        
        if form.is_valid():
            item = form.save(commit=False)
            item.created_by = request.user
            item.save()

            return redirect('item:detail', pk=item.id)

    else:
        form = NewItemForm(initial={'category': 'default_category_value'})
    categories = Category.objects.all()

    return render(request, 'item/form.html',{
        'form':form,
        'title':'New item',
        'categories':categories,
    })

@login_required
def edit(request, pk):
    item = get_object_or_404(Item, pk=pk,created_by=request.user)

    if request.method == 'POST':
        form = EditItemForm(request.POST, request.FILES, instance=item)

        if form.is_valid():
            form.save()

            return redirect('item:detail', pk=item.id)

    else:
        form = EditItemForm(instance=item)

    return render(request, 'item/form.html',{
        'form':form,
        'title':'Edit item',
    })


@login_required
def delete(request,pk):
    item = get_object_or_404(Item, pk=pk,created_by=request.user)
    item.delete()
    return redirect('dashboard:index')

item/templates/item/detail.html
{% extends 'core/base.html' %}

{% block title %}{{ item.name }}{% endblock title %}

{% block content %}

<div class="sm:grid grid-cols-5 gap-6">
    <div class="col-span-3 m-3 ">
        <img src="{{ item.image.url }}" class="rounded-xl max-w-[70%]  m-auto  dark:brightness-100" alt="">
    </div>

    <div class="col-span-2 p-6 bg-gray-100 dark:text-white dark:bg-gray-800 rounded-xl text-center md:text-left">
        <h1 class="mb-6 relative sm:text-3xl text-lg text-center">{{item.name}}
            {% if item.is_sold == True %}
            <span class="inline-block md:absolute right-0 sm:text-lg text-sm bg-red-400 py-1 px-2 rounded-xl text-white">Sold out</span>
            {% else %}
            <span class="inline-block md:absolute right-0 sm:text-lg text-sm bg-green-400 py-1 px-2 rounded-xl text-white">In stock</span>
            {% endif %}

        </h1>

        <div class="sm:flex flex-col justify-between md:w-3/4">
            <div>
                <h1 class="text-gray-500 dark:text-white md:text-3xl text-left">₹{{item.price}}</h1>
            </div>
            {% if item.size %}
            <div>
                <p>Size: {{ item.size }}</p>
            </div>
            {% endif %}
            {% if item.color %}
            
                <p>Colors: {{ item.color }}</p>
            {%  endif %}

            {% if item.gender %}
            <div>
                <p>Gender: {{ item.gender }}</p>
            </div>
            {% endif %}
        </div>


        {% if request.user == item.created_by %}
        <div class="mt-6 p-6 bg-white dark:bg-gray-900  dark:text-white rounded-xl text-center md:text-left   ">
            <p>This is your item!</p>
            <a href="{% url 'item:edit' item.id %}" class="inline-block   mt-6 px-6 py-3 text-lg font-semibold bg-yellow-500 text-white rounded-xl">Edit</a>
            <a href="{% url 'item:delete'  item.id %}" class="inline-block   mt-6 px-6 py-3 text-lg font-semibold bg-red-500 text-white rounded-xl">Delete</a>
        </div>
        {% else %}  
        <a href="{% url 'conversation:new' item.id %}" class="inline-block mt-6 px-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded-3xl hover:bg-teal-700">Connect {{item.created_by.username}}</a>
        {% comment %} <a href="{% url 'payment:payment' item.id %}" class="inline-block mt-6 px-6 py-3 text-lg font-semibold bg-orange-500 text-white rounded-3xl hover:bg-orange-700">Buy now</a> {% endcomment %}

        {% endif %}

        {% if item.description %}
        <p class="text-gray-700 dark:text-white">
            <strong class="text-gray-500 dark:text-white">Description:</strong>
            <br>
            {{item.description}}
        </p>
        {% endif %}
        
    </div>

</div>


<div class="mt-6 px-6 py-12 bg-gray-100 dark:text-white dark:bg-gray-800 rounded-xl">
    <h2 class="mb-6 text-2xl text-center">Related items</h2>

    <div class="grid md:grid-cols-5 grid-cols-2 gap-3">
        {% for item in related_items %}
            <div>
                <a href="{% url 'item:detail' item.id %}">
                    <div class="md-shrink-0">
                        <img src="{{ item.image.url }}" class="rounded-t-xl dark:brightness-50">
                    </div>
                    <div class="p-3 bg-white dark:text-white dark:bg-gray-900 rounded-b-xl ">
                        <h2 class="sm:text-xl break-words">{{ item.name }}</h2>
                        <h1 class="text-gray-500 ">{{item.price}}</h1>
                    </div>
                </a>    
            </div>

        {% endfor %}

    </div>
</div>

{% endblock content %}

item/templates/item/form.html
{% extends 'core/base.html' %}
{% block title %}{{ title }}{% endblock  %}

{% block content %}

<h1 class="mb-6 text-3xl dark:text-white text-center">{{ title }}</h1>

<form action="" method="POST" enctype="multipart/form-data">

    {% csrf_token %}
    <div class="flex flex-col items-center justify-center dark:text-black">
        <div class="space-y-4 flex flex-col justify-center dark:text-white  md:w-1/2 dark:bg-gray-800 p-6 rounded-xl shadow-xl">
            {{ form.as_p }} 
            {% if form.errors or form.non_field_errors %}
            <div class="mb-3 p-6 bg-red-100 dark:bg-red-500 rounded-xl">
                {% for field in form %}
                    {{ field.errors }}
                {% endfor %}
            {{ form.non_field_errors }}
            </div>
            {% endif %}
            <button class="mt-6 w-full py-4 px-8 text-lg bg-teal-500 hover:bg-teal-700 rounded-3xl text-white">Submit</button>

        </div>
        </div>

</form>
{% endblock content %}

item/templates/item/items.html
{% extends 'core/base.html' %}

{% block title %}Items{% endblock title %}

{% block content %}

    <div class="pb-6 sm:grid grid-cols-4 gap-4">
        <div class="col-span1">
            <form class="flex items-center flex-col" action="{% url 'item:items' %}" method="get">

                <input type="text" name="query" class="w-full py-4 px-6 border  rounded-3xl" value="{{query}}" required placeholder="Search what you want...">

                <button class="mt-2 py-2 px-8 text-lg bg-teal-500 text-white rounded-3xl ">Search</button>
            </form>

            <hr class="my-6">

            <div class="hidden sm:block">
                <p class="font-semibold relative w-full dark:text-white">Categories

                    <a href="{% url 'item:items' %}" class="absolute right-0 text-red-500">Clear</a>
                </p>
                <ul>
                    {% for category in categories %}
                        <li class="py-2 px-2 dark:text-white rounded-xl {% if category.id == category_id %} bg-gray-500 text-white {% endif %}">
                            <a href="{% url 'item:items' %}?query={{ query }}&category={{ category.id }}" >{{category.name}}</a>
                        </li>
                    {% endfor %}

                </ul>
            </div>
            

        </div>
        <div class="sm:col-span-3">
            <!-- <div class="grid grid-cols-3 gap-3  ">
                {% if items %}
                {% for item in items %}
                    <div class="shadow-lg h-fit rounded-xl m-3 hover:shadow-2xl">
                        <a href="{% url 'item:detail' item.id %}">
                            <div>
                                <img src="{{ item.image.url }}" class="w-full" alt="">
                            </div>
                            <div class="p-6 bg-gray-100  rounded-b-xl">
                                <h2 class="text-2xl">{{ item.name }}</h2>
                                <p class="text-gray-500">${{item.price}}</p>
                            </div>
                        </a>
                    </div>

                {% endfor %}

                {% else %}
                <div class="w-full col-span-3 p-12 flex justify-center bg-gray-200 rounded-xl">
                <h1 class="text-2xl font-normal">No items found!</h1>
                </div>

                {% endif %}
    
            </div> -->

                {% if items %}
                <div class="row ">

                {% for item in items %}
                    <div class="column m-2  ">
                        
                        <a href="{% url 'item:detail' item.id %}" class="">
                            <div class="    ">
                                <img src="{{ item.image.url }}" class="w-full rounded-t-xl dark:brightness-50   hover:drop-shadow-xl" alt="">
                            </div>
                            <div class="p-6 bg-gray-100 dark:text-white dark:bg-gray-800  rounded-b-xl shadow-xl hover:shadow-2xl">
                                <h2 class="sm:text-2xl text-lg break-words">{{ item.name }}</h2>
                                <p class="light:text-gray-700">₹{{item.price}}</p>
                            </div>
                        </a>                    
                    </div>
                
                {% endfor %}
            </div>

                <style>
                    .row {
                    display: flex;
                    flex-wrap: wrap;
                    padding: 0 4px;

                    }

                    /* Create four equal columns that sits next to each other */
                    .column {
                    flex: 25%;
                    max-width: 50%;
                    padding: 0 4px;
                    height: fit-content;
                    }
                    

                    .column img {
                    margin-top: 8px;
                    vertical-align: middle;
                    width: 100%;
                    transition: .5s ease-in-out;

                    }


                    /* Responsive layout - makes the two columns stack on top of each other instead of next to each other */
                    @media screen and (max-width: 600px) {
                    .row {
                    display: flex;
                    flex-wrap: wrap;
                    padding: 0 4px;
                    height: auto;
                    }
                    .column {
                        flex: 0%;
                        max-width: 50%;
                    }

                }
                </style>


                {% else %}
                <div class="w-full col-span-3 p-12 flex justify-center bg-gray-200 rounded-xl">
                <h1 class="text-2xl font-normal">No items found!</h1>
                </div>

                {% endif %}
    
        </div>

    </div>



{% endblock content %}