core/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views
from .forms import LoginForm
app_name = 'core'

urlpatterns = [
    path('',views.index, name='index'),
    path('contact/', views.contact, name='contact' ),
    path('signup/',views.signup, name='signup'),
    path('login/', auth_views.LoginView.as_view(template_name='core/login.html',authentication_form = LoginForm), name='login'),
    path('logout/', views.logout_view, name='logout'),
]   

dashboard/urls.py
from django.urls import path, include
from . import views

app_name='dashboard'

urlpatterns = [
    path('',views.index, name='index'),
    path('delete/', views.deleteUsers, name='delete'),
    path('promote/<int:pk>/', views.promoteUser, name='promote'),
    path('add-category/', views.add_category, name='add_category'),
    path('items/', include('item.urls')),
]

item/urls.py
from django.urls  import path,include
from  . import views

app_name = 'item'

urlpatterns = [
    path('',views.items, name='items'),
    path('<int:pk>/', views.detail, name = 'detail'),
    path('new/',views.new, name='new'),
    path('<int:pk>/delete', views.delete, name = 'delete'),
    path('<int:pk>/edit', views.edit, name = 'edit'),


     
]

marketplace/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
urlpatterns = [
    path('',include('core.urls')),
    path('items/', include('item.urls')),
    path('admin/', admin.site.urls),
    path('dashboard/', include('dashboard.urls')),
    path('inbox/',include('conversation.urls')),

] +  static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

dashboard/models.py
from django import forms

dashboard/forms.py
from django import forms 
from django.contrib.auth.models import User
from item.models import Category

class CategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = ('name',)
        

dashboard/views.py
from django.shortcuts import render,get_object_or_404,redirect

from item.models import Item, Category
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from .forms import CategoryForm


@login_required
def index(request):
    items = Item.objects.filter(created_by = request.user)
    all_users = User.objects.all()
    categories = Category.objects.all()


    return render(request, 'dashboard/index.html',{
        'items':items,
        'all_users':all_users,
        'categories':categories,

    })

    
@login_required
def deleteUsers(request):
    if request.method == 'POST':
        user_id = request.POST.get('user_id')
        user = get_object_or_404(User, id=user_id)
        user.delete()
    return redirect('dashboard:index')



@login_required
def promoteUser(request,pk):
    try:
        user = User.objects.get(pk=pk)
    except User.DoesNotExist:
        return redirect('dashboard:index')  # Redirect to the desired page if user doesn't exist

    user.is_staff = not user.is_staff
    user.is_superuser = not user.is_superuser
    user.save()
    return redirect('dashboard:index')

@login_required
def add_category(request):
    if request.method == 'POST':
        form = CategoryForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('dashboard:index')
    else:
        form = CategoryForm()

    categories = Category.objects.all()
    return render(request, 'dashboard/add_category.html', {
        'form': form,
        'categories':categories,
        })

dashboard/templates/dashboard/add_category.html
{% extends 'core/base.html' %}
{% block title %}Add Category{% endblock  %}
{% block content %}
<!-- add_category.html -->
<div class="w-full bg-gray-100 dark:bg-gray-800  p-12 mt-3 rounded-xl shadow-xl flex flex-col items-center">
    <h1 class="text-2xl font-medium text-center dark:text-white mb-12">Add Category</h1>
    {% if form.errors or form.non_field_errors %}
    <div class="mb-3 p-6 bg-red-100 rounded-xl">
        {% for field in form %}
            {{ field.errors }}
        {% endfor %}
        {{ form.non_field_errors }}
    </div>
    {% endif %}
    <form method="POST" class="w-3/4 flex flex-row justify-center items-center" >
        {% csrf_token %}
        <!-- {{ form.as_p }} -->
        <!-- <label for="category_list">Enter your new item:</label> -->
        <input class="w-1/2 p-3 m-3 rounded-full shadow-xl text-center text-xl" type="text" name="name" list="category_list" placeholder="Enter your new item...">
        <datalist id="category_list" >
            {% for category in categories %}
                <option value="{{ category.name }}">{{ category.name }}</option>
            {% endfor %}
        </datalist>
        <button type="submit" class="font-medium text-xl  ml-3 bg-teal-400 text-white w-fit py-3 px-6 text-center rounded-full shadow-xl hover:bg-teal-700">Add</button>

    </form>
</div>

  
{% endblock content %}

dashboard/templates/dashboard/index.html
{% extends 'core/base.html' %}

{% block title %}Dashboard {% endblock title %}

{% block content %}

{% if request.user.is_superuser == True %}


<div class="bg-gray-100 dark:text-white dark:bg-gray-800 sm:p-6 p-3 rounded-xl max-h-[70vh] overflow-y-scroll">
    <h1 class="text-center font-medium sm:text-3xl text-lg sm:mb-6 ">Welcome Superuser - {{request.user}}</h1>
    <p class="text-center">Total users: {{ all_users.count }}</p>
    <form action="{% url 'dashboard:delete' %}" method="POST" class="md:m-6">
        {%  csrf_token %}
            <table class="m-auto">
                <th>Username</th>
                <th>Email</th>
                <th>Date joined</th>
                <th>Last login</th>
                <th>Superuser</th>
                <th>Delete</th>        

            
            {% for user in all_users %}


            <tr class="dark:text-black   ">
            <td>
            <input type="text" readonly name="username" value="{{ user.username}}"  class="p-3 m-2   rounded-xl shadow-lg"  placeholder="Username"/>
            </td>

            <td>
                <input type="email" readonly name="email" value="{{ user.email}}"  class="p-3 m-2 rounded-xl shadow-lg"  placeholder="Email"/>
            </td>

            <td>
                <input type="text" name="date_joined" readonly value="{{ user.date_joined}}"  class="p-3 m-2 rounded-xl shadow-lg"  placeholder="Username"/>
            </td>

            <td>
                <input type="text" name="last_login" readonly value="{{ user.last_login}}"  class="p-3 m-2 rounded-xl shadow-lg"  placeholder="Username"/>
            </td>
            <td>
                <a class="p-3 m-2 rounded-xl shadow-lg {% if user.is_superuser %} bg-green-700  text-white hover:bg-green-500 {%  else %} bg-red-400  text-white hover:bg-red-500  {% endif  %}" href="{% url 'dashboard:promote' user.pk %}">
                    {{ user.is_superuser }}</a>
            </td>
            <td>
                <input type="hidden" name="user_id" value="{{ user.id }}">
                <button  class="p-3 m-2 shadow-lg rounded-xl bg-red-400 text-white hover:bg-red-500">Delete</button>
            </td>


            </tr>
            {% if form.errors or form.non_field_errors %}
            <div class="mb-3 p-6 bg-red-100 dark:bg-red-500 rounded-xl">
                {% for field in form %}
                    {{ field.errors }}
                {% endfor %}
                {{ form.non_field_errors }}
            </div>
            {% endif %}

            {% endfor %}
        
            </table>
        </form>


</div>

<div class="mt-6 px-6 py-12 bg-gray-100 dark:bg-gray-800  rounded-xl shadow-2xl">
    <h2 class="mb-12 sm:text-2xl text-lg text-center font-medium dark:text-white">Categories ({{ categories.count}})</h2>

    <div class="grid sm:grid-cols-3 grid-cols-2 gap-3">
        <a href="{% url 'dashboard:add_category' %}" class=" p-6 bg-teal-400 rounded-xl shadow-xl sm:text-2xl text-xl text-center text-white font-medium  hover:bg-teal-700"><h1>+</h1>Add new </a>
        {% for category in categories %}

        <div>
            <a href="{% url 'item:items' %}?category={{category.id}}" class="text-center">
                <div class="sm:p-6 p-3 bg-white dark:bg-gray-900 dark:text-white  rounded-xl shadow-xl">
                    <h2 class="sm:text-2xl text-lg break-words">{{ category.name }}</h2>
                    <p class="text-gray-500">{{category.items.count}} items</p>
                </div>
            </a>
        </div>


        {% endfor %}
    </div>
</div>
{% endif %}
    <div class="mt-6 px-6 py-12 bg-gray-100 dark:bg-gray-800 dark:text-white rounded-xl">
        <h2 class="sm:mb-12 mb-3 sm:text-2xl text-xl text-center font-medium">My items</h2>
        <div class="grid sm:grid-cols-3 grid-cols-2 gap-3">
            {% if items %}
            {% for item in items %}

                <div class="shadow-xl h-fit  rounded-b-xl ">
                    <a href="{% url 'item:detail' item.id %}">
                        <div class="md:shrink-0">
                            <img src="{{ item.image.url }}" class="w-full {% if item.is_sold == True %} grayscale {% endif %}" alt="">
                        </div>
                        <div class="sm:p-6 p-3 bg-gray-100 md:flex dark:bg-gray-900 dark:text-white  md:justify-between justify-center rounded-b-xl ">
                            <div>
                                <h2 class="sm:text-2xl text-lg">{{ item.name }}</h2>
                                <p class="text-gray-500">${{item.price}}</p>
                            </div>
                            <div >
                                {% if item.is_sold == True %}
                                <span class="inline-block   sm:text-lg text-sm bg-red-400 py-1 px-2 rounded-xl text-white">Sold out</span>
                                {% else %}
                                <span class="inline-block   sm:text-lg text-sm bg-green-400 py-1 px-2 rounded-xl text-white">In stock</span>
                                {% endif %}
                            </div>
                        </div>
                    </a>
                </div>

            {% endfor %}
            {% else %}
            <div class="w-full col-span-3 p-12 flex justify-center shadow-lg flex-col items-center  bg-gray-200 rounded-xl">
                <h1 class="sm:text-2xl text-center text-xl font-normal">You have no items!</h1>
                <a href="{% url 'item:new' %}" class="underline mt-3">Add now</a>
            </div>
            {% endif %}


        </div>
    </div>
{% endblock %}